
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_STARTUP_CLASS_H__
#define __VCLS_RG_VOLCANO_APP_RG_STARTUP_CLASS_H__

namespace rg_volcano_app
{

class rg_startup_class : public rg_volcano_base::rg_ChengXuLei
{
    DECLARE_VOL_CLASS (rg_volcano_app, rg_startup_class)

public:
    INT rg_startup_method ();
    inline_ rg_startup_class () { }
    inline_ void _VolObjectInitMembers () { }
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

protected:
    rg_my_main_window rg_ZhuChuangKou;
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_STARTUP_CLASS_H__
