
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIDAIMAKUANG_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIDAIMAKUANG_H__

namespace rg_xc_gui
{

class rg_XuanCaiDaiMaKuang : public rg_XuanCaiBianJiKuang
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiDaiMaKuang)

public:
            int OnEditChangeRows(HELE hEle,int iRow, int nRows, BOOL *pbHandled);
            int OnEditorSetBreakpoint(HELE hEle,int iRow, BOOL bCheck, BOOL *pbHandled);
            int OnEditorRemoveBreakpoint(HELE hEle,int iRow, BOOL *pbHandled) ;
            int OnEditorBreakpointChanged(HELE hEle,int iRow, int nChangeRows, BOOL *pbHandled) ;
            int OnEditorAutoMatchSelect(HELE hEle,int iRow, int nRows, BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing27);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing28);
    INT rg_DaiMaKuang_DuoHangNeiRongGaiBian (INT64 rg_DaiMaKuangGouBing, INT rg_KaiShiHang1, INT rg_GaiBianHangShuLiang, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie118);
    INT rg_DaiMaKuang_SheZhiDuanDian (INT64 rg_DaiMaKuangGouBing1, INT rg_KaiShiHang2, BOOL rg_ShiFou1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie119);
    INT rg_DaiMaKuang_YiChuDuanDian (INT64 rg_DaiMaKuangGouBing2, INT rg_KaiShiHang3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie120);
    INT rg_DaiMaKuang_DuanDianGaiBian (INT64 rg_DaiMaKuangGouBing3, INT rg_KaiShiHang4, INT rg_GaiBianHangShu, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie121);
    INT rg_DaiMaKuang_ZiDongXuanZe (INT64 rg_DaiMaKuangGouBing4, INT rg_KaiShiHang5, INT rg_GaiBianHangShuLiang1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie122);
    virtual INT64 rg_ChuangJian9 (INT rg_ZuoBian47, INT rg_DingBian47, INT rg_KuanDu54, INT rg_GaoDu53, INT64 rg_FuGouBing21);
    inline_ rg_XuanCaiDaiMaKuang () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiDaiMaKuang_DaiMaKuang_DuoHangNeiRongGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiDaiMaKuang_DaiMaKuang_SheZhiDuanDian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiDaiMaKuang_DaiMaKuang_YiChuDuanDian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiDaiMaKuang_DaiMaKuang_DuanDianGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiDaiMaKuang_DaiMaKuang_ZiDongXuanZe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_120;
    CVolEventReceiver rw_121;
    CVolEventReceiver rw_122;
    CVolEventReceiver rw_123;
    CVolEventReceiver rw_124;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIDAIMAKUANG_H__
