
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_FUDONGCHUANGKOU1_H__
#define __VCLS_RG_XC_GUI_RG_FUDONGCHUANGKOU1_H__

namespace rg_xc_gui
{

class rg_FuDongChuangKou1 : public WinBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_FuDongChuangKou1)

public:
    inline_ rg_FuDongChuangKou1(HWINDOW Window):rg_FuDongChuangKou1()    {
        data().SetP((vint)Window);
    }

public:
    inline_ rg_FuDongChuangKou1 () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_FUDONGCHUANGKOU1_H__
