
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_ZHENGSHULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_ZHENGSHULEI_H__

namespace rg_volcano_base
{

class rg_ZhengShuLei : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_ZhengShuLei)

public:
    virtual void* GetDataPtr () override  { return &rg_value3; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_value3); }

public:
    rg_ZhengShuLei ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    INT rg_value3;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_ZHENGSHULEI_H__
