
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIYUELIKUANG_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIYUELIKUANG_H__

namespace rg_xc_gui
{

class rg_XuanCaiYueLiKuang : public XEleBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiYueLiKuang)

public:
           int OnCalendarChange(HELE hEle,BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing43);
    INT rg_YueLiKuang_RiJiGaiBian (INT64 rg_YueLiKuangGouBing, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie137);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing44);
    inline_ rg_XuanCaiYueLiKuang () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiYueLiKuang_YueLiKuang_RiJiGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_139;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIYUELIKUANG_H__
