
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_XWIDGET_H__
#define __VCLS_RG_XC_GUI_XWIDGET_H__

namespace rg_xc_gui
{

class XWidget : public widgetUI
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, XWidget)

public:
    virtual BOOL rg_ShiFouXianShi2 ();
    inline_ XWidget () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_XWIDGET_H__
