
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_KUANGJIACHUANGKOU_H__
#define __VCLS_RG_XC_GUI_RG_KUANGJIACHUANGKOU_H__

namespace rg_xc_gui
{

class rg_KuangJiaChuangKou : public WinBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_KuangJiaChuangKou)

public:
           int OnWndFloatPane(HWINDOW hWindow, HWINDOW hFloatWnd, HELE hPane, BOOL *pbHandled);
            int OnWndLayoutViewRect(HWINDOW hWindow,int width, int height, BOOL *pbHandled);

public:
    INT rg_KuangJiaChuangKou_FuDongChuangGe (INT64 rg_ChuangKouGouBing46, rg_FuDongChuangKou1& rg_FuDongChuangKou, INT64 rg_YuanSuGouBing4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie40);
    INT rg_KuangJiaChuangKou_ZhuShiTuZuoBiaoGaiBian (INT64 rg_ChuangKouGouBing47, INT rg_KuanDu19, INT rg_GaoDu19, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie41);
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian (INT rg_ShiJianLeiXing6);
    virtual void rg_YiChuShiJian (INT rg_ShiJianLeiXing7);
    inline_ rg_KuangJiaChuangKou () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_KuangJiaChuangKou_KuangJiaChuangKou_FuDongChuangGe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_KuangJiaChuangKou_KuangJiaChuangKou_ZhuShiTuZuoBiaoGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_42;
    CVolEventReceiver rw_43;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_KUANGJIACHUANGKOU_H__
