
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAICAICHAN_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAICAICHAN_H__

namespace rg_xc_gui
{

class rg_XuanCaiCaiChan : public xcguibase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiCaiChan)

public:
    inline_ rg_XuanCaiCaiChan(vint menu):rg_XuanCaiCaiChan()    {
        data().SetP(menu);
    }

public:
    inline_ rg_XuanCaiCaiChan () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAICAICHAN_H__
