
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_BIANZHENGSHUSHUZULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_BIANZHENGSHUSHUZULEI_H__

namespace rg_volcano_base
{

class rg_BianZhengShuShuZuLei : public rg_KuoZhanDuiXiangLei
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_BianZhengShuShuZuLei)

public:
    inline_ void _CopySelfFromExtra (const rg_BianZhengShuShuZuLei& objCopyFrom)
    {
        m_aryData.Copy (objCopyFrom.m_aryData);
    }
    inline_ BOOL _IsSelfEqualExtra (const rg_BianZhengShuShuZuLei& objCompare) const
    {
        return (BOOL)m_aryData.IsEqual (objCompare.m_aryData);
    }
    inline_ CMArray<INT64>& data ()
    {
        return m_aryData;
    }
    CMArray<INT64> m_aryData;

public:
    virtual void GetDumpString (CVolString& rg_ZhanShiNeiRong4, INT rg_ZuiDaZhanShiShuJuCheCun4);
    virtual void LoadFromStream (CVolBaseInputStream& rg_LiuDuiXiang8);
    virtual void SaveIntoStream (CVolBaseOutputStream& rg_LiuDuiXiang9);
    inline_ rg_BianZhengShuShuZuLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_BIANZHENGSHUSHUZULEI_H__
