
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAILIEBIAOSHITU_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAILIEBIAOSHITU_H__

namespace rg_xc_gui
{

class rg_XuanCaiLieBiaoShiTu : public rg_XuanCaiGunDongShiTu
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiLieBiaoShiTu)

public:
           int OnListViewTemplateCreate(HELE hEle,listView_item_* pItem,int nFlag, BOOL *pbHandled);
           int OnListViewTemplateCreateEnd(HELE hEle,listView_item_* pItem,int nFlag, BOOL *pbHandled);
           int OnListViewTemplateDestroy(HELE hEle,listView_item_* pItem,int nFlag, BOOL *pbHandled);
           int OnListViewDrawItem(HELE hEle,HDRAW hDraw,listView_item_* pItem,BOOL *pbHandled);
           int OnListViewSelect(HELE hEle,int iGroup,int iItem,BOOL *pbHandled);
           int OnListViewExpand(HELE hEle,int iGroup,BOOL bExpand,BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing21);
    INT rg_LieBiaoShiTu_XiangMoBanChuangJian (INT64 rg_LieBiaoGouBing11, rg_LieBiaoShiTu_XiangJieGou& rg_XiangJieGou4, INT rg_ZhuangTaiBiaoShi3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie98);
    INT rg_LieBiaoShiTu_XiangMoBanChuangJianWanCheng (INT64 rg_LieBiaoGouBing12, rg_LieBiaoShiTu_XiangJieGou& rg_XiangJieGou5, INT rg_ZhuangTaiBiaoShi4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie99);
    INT rg_LieBiaoShiTu_XiangMoBanXiaoHui (INT64 rg_LieBiaoGouBing13, rg_LieBiaoShiTu_XiangJieGou& rg_XiangJieGou6, INT rg_ZhuangTaiBiaoShi5, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie100);
    INT rg_LieBiaoShiTu_XiangHuiZhi (INT64 rg_LieBiaoGouBing14, rg_XuanCaiHuiTu& rg_KaiShiHuiTu12, rg_LieBiaoShiTu_XiangJieGou& rg_XiangJieGou7, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie101);
    INT rg_LieBiaoShiTu_XiangXuanZe (INT64 rg_LieBiaoGouBing15, INT rg_ZuSuoYin, INT rg_XiangSuoYin31, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie102);
    INT rg_LieBiaoShiTu_XiangZhanKai (INT64 rg_LieBiaoGouBing16, INT rg_ZuSuoYin1, BOOL rg_ZhanKaiShouSu, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie103);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing22);
    virtual INT64 rg_ChuangJian9 (INT rg_ZuoBian41, INT rg_DingBian41, INT rg_KuanDu43, INT rg_GaoDu42, INT64 rg_FuGouBing15);
    inline_ rg_XuanCaiLieBiaoShiTu () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiLieBiaoShiTu_LieBiaoShiTu_XiangMoBanChuangJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShiTu_LieBiaoShiTu_XiangMoBanChuangJianWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShiTu_LieBiaoShiTu_XiangMoBanXiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShiTu_LieBiaoShiTu_XiangHuiZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShiTu_LieBiaoShiTu_XiangXuanZe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShiTu_LieBiaoShiTu_XiangZhanKai (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_100;
    CVolEventReceiver rw_101;
    CVolEventReceiver rw_102;
    CVolEventReceiver rw_103;
    CVolEventReceiver rw_104;
    CVolEventReceiver rw_105;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAILIEBIAOSHITU_H__
