
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_ZIFULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_ZIFULEI_H__

namespace rg_volcano_base
{

class rg_ZiFuLei : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_ZiFuLei)

public:
    virtual void* GetDataPtr () override  { return &rg_value2; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_value2); }

public:
    rg_ZiFuLei ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    TCHAR rg_value2;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_ZIFULEI_H__
