
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIBUJUKUANGJIA_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIBUJUKUANGJIA_H__

namespace rg_xc_gui
{

class rg_XuanCaiBuJuKuangJia : public rg_XuanCaiGunDongShiTu
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiBuJuKuangJia)

public:
    virtual INT64 rg_ChuangJian9 (INT rg_ZuoBian38, INT rg_DingBian38, INT rg_KuanDu37, INT rg_GaoDu36, INT64 rg_FuGouBing11);
    inline_ rg_XuanCaiBuJuKuangJia () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIBUJUKUANGJIA_H__
