
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_XCGUIBASE_H__
#define __VCLS_RG_XC_GUI_XCGUIBASE_H__

namespace rg_xc_gui
{

class xcguibase : public rg_xcbase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, xcguibase)

public:
    inline_ xcguibase () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_XCGUIBASE_H__
