
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_CHUANGKOUCHENGXULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_CHUANGKOUCHENGXULEI_H__

namespace rg_volcano_base
{

class rg_ChuangKouChengXuLei : public rg_ChengXuLei
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_ChuangKouChengXuLei)

public:
    virtual BOOL rg_XiaoXiGuoLu (INT64 rg_ChuangKouGouBing2, INT rg_XiaoXiZhi, INT64 rg_XiaoXiCanShu, INT64 rg_XiaoXiCanShu1, INT64 rg_XiaoXiDeZhi);
    virtual BOOL rg_KongXian1 (INT rg_YiKongXianShiJian);
    virtual void rg_JiJiangTuiChu ();
    inline_ rg_ChuangKouChengXuLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_CHUANGKOUCHENGXULEI_H__
