
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_LUOJIXINGLEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_LUOJIXINGLEI_H__

namespace rg_volcano_base
{

class rg_LuoJiXingLei : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_LuoJiXingLei)

public:
    virtual void* GetDataPtr () override  { return &rg_value8; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_value8); }

public:
    rg_LuoJiXingLei ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    BOOL rg_value8;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_LUOJIXINGLEI_H__
