
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XINGZHUANGJILEI_H__
#define __VCLS_RG_XC_GUI_RG_XINGZHUANGJILEI_H__

namespace rg_xc_gui
{

class rg_XingZhuangJiLei : public XWidget
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XingZhuangJiLei)

public:
    inline_ rg_XingZhuangJiLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XINGZHUANGJILEI_H__
