
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_KESHEJILEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_KESHEJILEI_H__

namespace rg_volcano_base
{

class rg_KeSheJiLei : public CVolRefObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_KeSheJiLei)

public:
    virtual CVolString VolGetDesignContent ();
    inline_ rg_KeSheJiLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_KESHEJILEI_H__
