
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_XCKLEI_H__
#define __VCLS_RG_XC_GUI_XCKLEI_H__

namespace rg_xc_gui
{

class xcklei : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, xcklei)

public:
    static BOOL CALLBACK rg_XuanCai_ChuShiHua (BOOL bD2D);
    inline_ xcklei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_XCKLEI_H__
