
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAISHUXINGKUANG_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAISHUXINGKUANG_H__

namespace rg_xc_gui
{

class rg_XuanCaiShuXingKuang : public rg_XuanCaiGunDongShiTu
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiShuXingKuang)

public:
            int OnPGridValueChange(HELE hEle,int nItemID,BOOL *pbHandled);
            int OnPGridItemSet(HELE hEle,int nItemID, BOOL *pbHandled);
            int OnPGridItemSelect(HELE hEle,int nItemID, BOOL *pbHandled);
            int OnPGridItemAdjustCoordinate(HELE hEle,propertyGrid_item_* pItem, BOOL *pbHandled);
            int OnPGridItemDestroy(HELE hEle,int nItemID, BOOL *pbHandled);
            int OnPGridItemExpand(HELE hEle,int nItemID, BOOL bExpand, BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing45);
    INT rg_ShuXingKuang_XiangZhiGaiBian (INT64 rg_ShuXingKuangGouBing, INT rg_XiangID45, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie138);
    INT rg_ShuXingKuang_XiangSheZhi (INT64 rg_ShuXingKuangGouBing1, INT rg_XiangID46, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie139);
    INT rg_ShuXingKuang_XiangXuanZe (INT64 rg_ShuXingKuangGouBing2, INT rg_XiangID47, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie140);
    INT rg_ShuXingKuang_XiangDiaoZhengZuoBiao (INT64 rg_ShuXingKuangGouBing3, rg_ShuXingKuang_XiangJieGou& rg_pItem, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie141);
    INT rg_ShuXingKuang_XiangXiaoHui (INT64 rg_ShuXingKuangGouBing4, INT rg_XiangID48, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie142);
    INT rg_ShuXingKuang_XiangZhanKai (INT64 rg_ShuXingKuangGouBing5, INT rg_XiangID49, BOOL rg_ShiFouZhanKai6, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie143);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing46);
    virtual INT64 rg_ChuangJian9 (INT rg_ZuoBian61, INT rg_DingBian61, INT rg_KuanDu74, INT rg_GaoDu73, INT64 rg_FuGouBing33);
    inline_ rg_XuanCaiShuXingKuang () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiShuXingKuang_ShuXingKuang_XiangZhiGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiShuXingKuang_ShuXingKuang_XiangSheZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiShuXingKuang_ShuXingKuang_XiangXuanZe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiShuXingKuang_ShuXingKuang_XiangDiaoZhengZuoBiao (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiShuXingKuang_ShuXingKuang_XiangXiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiShuXingKuang_ShuXingKuang_XiangZhanKai (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_140;
    CVolEventReceiver rw_141;
    CVolEventReceiver rw_142;
    CVolEventReceiver rw_143;
    CVolEventReceiver rw_144;
    CVolEventReceiver rw_145;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAISHUXINGKUANG_H__
