
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIJINDUTIAO_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIJINDUTIAO_H__

namespace rg_xc_gui
{

class rg_XuanCaiJinDuTiao : public XEleBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiJinDuTiao)

public:
           int OnProgressBarChange(HELE hEle,int pos,BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing31);
    INT rg_process_bar_WeiZhiGaiBian (INT64 rg_JinDuTiaoGouBing, INT rg_WeiZhi18, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie127);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing32);
    inline_ rg_XuanCaiJinDuTiao () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiJinDuTiao_process_bar_WeiZhiGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_129;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIJINDUTIAO_H__
