
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_CHANJINGDUXIAOSHULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_CHANJINGDUXIAOSHULEI_H__

namespace rg_volcano_base
{

class rg_ChanJingDuXiaoShuLei : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_ChanJingDuXiaoShuLei)

public:
    virtual void* GetDataPtr () override  { return &rg_value6; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_value6); }

public:
    rg_ChanJingDuXiaoShuLei ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    FLOAT rg_value6;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_CHANJINGDUXIAOSHULEI_H__
