
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_CHENGXULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_CHENGXULEI_H__

namespace rg_volcano_base
{

class rg_ChengXuLei : public CVolUserApp
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_ChengXuLei)

public:
    virtual const CVolRuntimeClass** GetSpecialUserRuntimeClasses () const override;

public:
    inline_ rg_ChengXuLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_CHENGXULEI_H__
