
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_GUIBASE_H__
#define __VCLS_RG_XC_GUI_RG_GUIBASE_H__

namespace rg_xc_gui
{

class rg_guibase : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_guibase)

public:
    inline_ rg_guibase () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_GUIBASE_H__
