
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_base
{

BOOL CALLBACK rg_ChengXuDiaoShiLei::rg_ShiFouWeiDiaoShiBan ()
{
    #ifdef _DEBUG
        return TRUE;
    #else
        return FALSE;
    #endif
}

}
