
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VOL_USER_APP_STDAFX_H__
#define __VOL_USER_APP_STDAFX_H__

#ifndef VC_EXTRALEAN
    #define VC_EXTRALEAN
#endif

#include "targetver.h"

#include <sys\\base\\libs\\win_base\\vol_base.h>
#include <user\\XCGUI\\lib\\xcgui.h>
#include <user\\XCGUI\\lib\\wke.h>
#include <user\\XCGUI\\lib\\vol_xcgui.h>

#endif  // __VOL_USER_APP_STDAFX_H__
