
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIRIJIKUANG_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIRIJIKUANG_H__

namespace rg_xc_gui
{

class rg_XuanCaiRiJiKuang : public XEleBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiRiJiKuang)

public:
           int OnDateTimeChange(HELE hEle,BOOL *pbHandled);
           int OnDateTimePopupMonthCal(HELE hEle,HWINDOW hMonthCalWnd,HELE hMonthCal,BOOL *pbHandled);
           int OnDateTimeExitMonthCal(HELE hEle,HWINDOW hMonthCalWnd,HELE hMonthCal,BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing41);
    INT rg_RiJiKuang_NeiRongGaiBian (INT rg_RiJiKuangGouBing, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie134);
    INT rg_RiJiKuang_DanChuYueLi (INT rg_RiJiKuangGouBing1, INT rg_YueLiChuangKouGouBing, INT rg_YueLiYuanSuGouBing, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie135);
    INT rg_RiJiKuang_TuiChuYueLi (INT rg_RiJiKuangGouBing2, INT rg_YueLiChuangKouGouBing1, INT rg_YueLiYuanSuGouBing1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie136);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing42);
    inline_ rg_XuanCaiRiJiKuang () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiRiJiKuang_RiJiKuang_NeiRongGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiRiJiKuang_RiJiKuang_DanChuYueLi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiRiJiKuang_RiJiKuang_TuiChuYueLi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_136;
    CVolEventReceiver rw_137;
    CVolEventReceiver rw_138;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIRIJIKUANG_H__
