
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_WINBASE_H__
#define __VCLS_RG_XC_GUI_WINBASE_H__

namespace rg_xc_gui
{

class WinBase : public widgetUI
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, WinBase)

public:
            int OnWndDrawWindow(HWINDOW hWindow, HDRAW hDraw,BOOL *pbHandled);
            int OnWndClose(HWINDOW hWindow, BOOL *pbHandled);
            int OnWndDestroy(HWINDOW hWindow, BOOL *pbHandled);
            int OnWndNCDestroy(HWINDOW hWindow, BOOL *pbHandled);
            int OnWndMouseMove(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndLButtonDown(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndLButtonUp(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndRButtonDown(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndRButtonUp(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndLButtonDBClick(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndRButtonDBClick(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndMouseWheel(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndMouseHover(HWINDOW hWindow, UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnWndMouseLeave(HWINDOW hWindow, BOOL *pbHandled);
            int OnWndSize(HWINDOW hWindow, UINT nFlags,SIZE *pSize,BOOL *pbHandled);
            int OnWndTimer(HWINDOW hWindow, UINT nIDEvent,BOOL *pbHandled);
            int OnWndXCTimer(HWINDOW hWindow, UINT nTimerID,BOOL *pbHandled);
            int OnWndSetFocus(HWINDOW hWindow, BOOL *pbHandled);
            int OnWndKillFocus(HWINDOW hWindow, BOOL *pbHandled);
            int OnWndKeyDown(HWINDOW hWindow, WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnWndKeyUp(HWINDOW hWindow, WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnWndCaptureChanged(HWINDOW hWindow, HWND hWnd,BOOL *pbHandled);
            int OnWndSetCursor(HWINDOW hWindow, WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnWndChar(HWINDOW hWindow, WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnDropFiles(HWINDOW hWindow, HDROP hDropInfo , BOOL *pbHandled);
            int OnWndProc(HWINDOW hWindow, UINT message, WPARAM wParam, LPARAM lParam, BOOL *pbHandled);
            int OnWndMenuPopup(HWINDOW hWindow, HMENUX hMenu, BOOL *pbHandled);
            int OnWndMenuPopupWnd(HWINDOW hWindow, HMENUX hMenu,menu_popupWnd_ *pInfo,BOOL *pbHandled);
            int OnWndMenuSelect(HWINDOW hWindow, int nID,BOOL *pbHandled);
            int OnWndMenuExit(HWINDOW hWindow, BOOL *pbHandled);
            int OnWndMenuDrawBackground(HWINDOW hWindow, HDRAW hDraw,menu_drawBackground_ *pInfo,BOOL *pbHandled);
            int OnMenuDrawItem(HWINDOW hWindow, HDRAW hDraw,menu_drawItem_* pInfo,BOOL *pbHandled);
            int OnWndDrawWindowEnd(HWINDOW hWindow, HDRAW hDraw,BOOL *pbHandled);
            int OnWndDrawWindowDisplay(HWINDOW hWindow, BOOL *pbHandled);
            int OnCustomevent(HWINDOW hWindow, INT_P wParam,INT_P lParam,BOOL *pbHandled);
            int OnMove(HWINDOW hWindow,WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnWndDocPopup(HWINDOW hWindow,HWINDOW hWindowDock,  HELE hPane, BOOL *pbHandled);
            int OnWndFloatWndDrag(HWINDOW hWindow,HWINDOW hFloatWnd, HWINDOW* hArray, BOOL *pbHandled);
            int OnWndPaneShow(HWINDOW hWindow,HELE hPane, BOOL bShow, BOOL *pbHandled);
            int OnWndSYSKEYDOWN(HWINDOW hWindow, WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnWndSetFocusEle(HWINDOW hWindow,HELE hEle,BOOL *pbHandled);
            int OnWndTrayIcon(WPARAM wParam, LPARAM lParam, BOOL *pbHandled);
            NOTIFYICONDATA        m_NotifyIconData;

public:
    virtual void rg_ZhuCeShiJian (INT rg_ShiJianLeiXing1);
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_YiChuShiJian (INT rg_ShiJianLeiXing2);
    INT rg_win_HuiZhi (INT rg_ChuangKouGouBing3, rg_XuanCaiHuiTu& rg_KaiShiHuiTu, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie);
    INT rg_win_GuanBi (INT rg_ChuangKouGouBing4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie1);
    INT rg_win_XiaoHui (INT rg_ChuangKouGouBing5, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie2);
    INT rg_win_ShuBiaoYiDong (INT rg_ChuangKouGouBing6, INT rg_BiaoShi5, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie3);
    INT rg_win_ShuBiaoZuoJianAnXia (INT rg_ChuangKouGouBing7, INT rg_BiaoShi6, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie4);
    INT rg_win_ShuBiaoZuoJianDanQi (INT rg_ChuangKouGouBing8, INT rg_BiaoShi7, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie5);
    INT rg_win_ShuBiaoYouJianAnXia (INT rg_ChuangKouGouBing9, INT rg_BiaoShi8, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie6);
    INT rg_win_ShuBiaoYouJianDanQi (INT rg_ChuangKouGouBing10, INT rg_BiaoShi9, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie7);
    INT rg_win_ShuBiaoZuoJianShuangJi (INT rg_ChuangKouGouBing11, INT rg_BiaoShi10, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao5, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie8);
    INT rg_win_ShuBiaoYouJianShuangJi (INT rg_ChuangKouGouBing12, INT rg_BiaoShi11, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao6, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie9);
    INT rg_win_ShuBiaoGunLunGunDong (INT rg_ChuangKouGouBing13, INT rg_BiaoShi12, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao7, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie10);
    INT rg_win_ShuBiaoJinRu (INT rg_ChuangKouGouBing14, INT rg_BiaoShi13, rg_ZuoBiao_xc& rg_ShuBiaoZuoBiao8, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie11);
    INT rg_win_ShuBiaoLiKai (INT rg_ChuangKouGouBing15, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie12);
    INT rg_win_CheCunGaiBian (INT rg_ChuangKouGouBing16, INT rg_BiaoShi14, rg_CheCun_xc& rg_ChuangKouCheCun, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie13);
    INT rg_win_DingShiQi (INT rg_ChuangKouGouBing17, INT rg_ShiZhongID, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie14);
    INT rg_win_DingShiQiXuanCai (INT rg_ChuangKouGouBing18, INT rg_ShiZhongID1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie15);
    INT rg_win_HuoQuJiaoDian (INT rg_ChuangKouGouBing19, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie16);
    INT rg_win_ShiQuJiaoDian (INT rg_ChuangKouGouBing20, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie17);
    INT rg_win_AnJianAnXia (INT rg_ChuangKouGouBing21, INT rg_wParam, INT rg_lParam, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie18);
    INT rg_win_ShuBiaoBuHuoGaiBian (INT rg_XuanCaiGouBing, INT rg_ChuangKouGouBing22, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie19);
    INT rg_win_ZhiShuBiaoGuangBiao (INT rg_ChuangKouGouBing23, INT rg_wParam1, INT rg_lParam1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie20);
    INT rg_win_ShuRuZiFu (INT rg_ChuangKouGouBing24, INT rg_wParam2, INT rg_lParam2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie21);
    INT rg_win_WenJianTuoRu (INT rg_ChuangKouGouBing25, rg_volcano_base::rg_WenBenShuZuLei& rg_WenJianShuZu, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie22);
    INT rg_win_ChuLiGuoCheng (INT rg_ChuangKouGouBing26, INT rg_XiaoXi, INT rg_wParam3, INT rg_lParam3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie23);
    INT rg_win_CaiChanDanChu (INT rg_ChuangKouGouBing27, INT rg_CaiChanGouBing, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie24);
    INT rg_win_CaiChanDanChuChuangKou (INT rg_ChuangKouGouBing28, INT rg_CaiChanGouBing1, rg_CaiChan_DanChuChuangKouJieGou& rg_CaiChanXinXi, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie25);
    INT rg_win_CaiChanXuanZe (INT rg_ChuangKouGouBing29, INT rg_CaiChanID, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie26);
    INT rg_win_CaiChanTuiChu (INT rg_ChuangKouGouBing30, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie27);
    INT rg_win_CaiChanHuiZhiBeiJing (INT rg_ChuangKouGouBing31, rg_XuanCaiHuiTu& rg_KaiShiHuiTu1, rg_CaiChan_HuiZhiBeiJingJieGou& rg_BeiJingJieGou, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie28);
    INT rg_win_CaiChanXiangHuiZhi (INT rg_ChuangKouGouBing32, rg_XuanCaiHuiTu& rg_KaiShiHuiTu2, rg_CaiChan_HuiZhiXiangJieGou& rg_XiangJieGou, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie29);
    INT rg_win_HuiZhiWanCheng (INT rg_ChuangKouGouBing33, rg_XuanCaiHuiTu& rg_KaiShiHuiTu3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie30);
    INT rg_win_HuiZhiWanChengBingYiXianShi (INT rg_ChuangKouGouBing34, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie31);
    INT rg_win_WeiZhiGaiBian (INT rg_ChuangKouGouBing35, INT rg_wParam4, INT rg_lParam4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie32);
    INT rg_win_ZiDingYiShiJian (INT rg_ChuangKouGouBing36, INT rg_wParam5, INT rg_lParam5, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie33);
    INT rg_win_KuangJiaChuangKouMaTouDanChuChuangGe (INT rg_ChuangKouGouBing37, INT rg_DanChuChuangGeGouBing, INT rg_ChuangGeGouBing, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie34);
    INT rg_win_FuDongChuangKouTuoDong (INT rg_ChuangKouGouBing38, INT rg_FuDongChuangKouGouBing, rg_volcano_base::rg_BianZhengShuShuZuLei& rg_ChuangKouGouBingShuZu, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie35);
    INT rg_win_ChuangGeXianShiYinCang (INT rg_ChuangKouGouBing39, INT rg_ChuangGeGouBing1, BOOL rg_ShiFouXianShi4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie36);
    INT rg_win_AnJianDanQi (INT rg_ChuangKouGouBing40, INT rg_wParam6, INT rg_lParam6, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie37);
    INT rg_win_JiTongAnJianAnXia (INT rg_ChuangKouGouBing41, INT rg_wParam7, INT rg_lParam7, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie38);
    INT rg_win_HuoDeJiaoDian_YuanSu (INT rg_ChuangKouGouBing42, INT rg_YuanSuGouBing, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie39);
    inline_ WinBase () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_WinBase_win_HuiZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_GuanBi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_XiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoYiDong (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoZuoJianAnXia (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoZuoJianDanQi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoYouJianAnXia (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoYouJianDanQi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoZuoJianShuangJi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoYouJianShuangJi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoGunLunGunDong (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoJinRu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoLiKai (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_CheCunGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_DingShiQi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_DingShiQiXuanCai (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_HuoQuJiaoDian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShiQuJiaoDian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_AnJianAnXia (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuBiaoBuHuoGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ZhiShuBiaoGuangBiao (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ShuRuZiFu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_WenJianTuoRu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ChuLiGuoCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_CaiChanDanChu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_CaiChanDanChuChuangKou (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_CaiChanXuanZe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_CaiChanTuiChu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_CaiChanHuiZhiBeiJing (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_CaiChanXiangHuiZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_HuiZhiWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_HuiZhiWanChengBingYiXianShi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_WeiZhiGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ZiDingYiShiJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_KuangJiaChuangKouMaTouDanChuChuangGe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_FuDongChuangKouTuoDong (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_ChuangGeXianShiYinCang (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_AnJianDanQi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_JiTongAnJianAnXia (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_WinBase_win_HuoDeJiaoDian_YuanSu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_2;
    CVolEventReceiver rw_3;
    CVolEventReceiver rw_4;
    CVolEventReceiver rw_5;
    CVolEventReceiver rw_6;
    CVolEventReceiver rw_7;
    CVolEventReceiver rw_8;
    CVolEventReceiver rw_9;
    CVolEventReceiver rw_10;
    CVolEventReceiver rw_11;
    CVolEventReceiver rw_12;
    CVolEventReceiver rw_13;
    CVolEventReceiver rw_14;
    CVolEventReceiver rw_15;
    CVolEventReceiver rw_16;
    CVolEventReceiver rw_17;
    CVolEventReceiver rw_18;
    CVolEventReceiver rw_19;
    CVolEventReceiver rw_20;
    CVolEventReceiver rw_21;
    CVolEventReceiver rw_22;
    CVolEventReceiver rw_23;
    CVolEventReceiver rw_24;
    CVolEventReceiver rw_25;
    CVolEventReceiver rw_26;
    CVolEventReceiver rw_27;
    CVolEventReceiver rw_28;
    CVolEventReceiver rw_29;
    CVolEventReceiver rw_30;
    CVolEventReceiver rw_31;
    CVolEventReceiver rw_32;
    CVolEventReceiver rw_33;
    CVolEventReceiver rw_34;
    CVolEventReceiver rw_35;
    CVolEventReceiver rw_36;
    CVolEventReceiver rw_37;
    CVolEventReceiver rw_38;
    CVolEventReceiver rw_39;
    CVolEventReceiver rw_40;
    CVolEventReceiver rw_41;
};

}

#endif  //__VCLS_RG_XC_GUI_WINBASE_H__
