
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_APP_RG_MY_MAIN_WINDOW_H__
#define __VCLS_RG_VOLCANO_APP_RG_MY_MAIN_WINDOW_H__

namespace rg_volcano_app
{

class rg_my_main_window : public rg_xc_gui::rg_XuanCaiKeSheJiLei
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_app, rg_my_main_window)

public:
    virtual void rg_ChuangJianWanCheng1 ();
    virtual CVolString VolGetDesignContent ();
    inline_ rg_my_main_window () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_APP_RG_MY_MAIN_WINDOW_H__
