
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_XELEBASE_H__
#define __VCLS_RG_XC_GUI_XELEBASE_H__

namespace rg_xc_gui
{

class XEleBase : public XWidget
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, XEleBase)

public:
            int OnEventProc(HELE hEle,UINT nEvent, WPARAM wParam, LPARAM lParam, BOOL *pbHandled);
            int OnDraw(HELE hEle,HDRAW hDraw,BOOL *pbHandled);
            int OnPaintEnd(HELE hEle,HDRAW hDraw,BOOL *pbHandled);
            int OnDrawScrollView(HELE hEle,HDRAW hDraw,BOOL *pbHandled);
            int OnMouseMove(HELE hEle,UINT nFlags, POINT *pPt, BOOL *pbHandled);
            int OnMouseStay(HELE hEle,BOOL *pbHandled);
            int OnMouseHover(HELE hEle,UINT nFlags, POINT *pPt, BOOL *pbHandled);
            int OnMouseLeave(HELE hEle,HELE hEleStay,BOOL *pbHandled);
            int OnMouseWheel(HELE hEle,UINT nFlags,POINT *pPt,BOOL *pbHandled);
            int OnLButtonDown(HELE hEle,UINT nFlags, POINT *pPt,BOOL *pbHandled);
            int OnLButtonUp(HELE hEle,UINT nFlags, POINT *pPt,BOOL *pbHandled);
            int OnRButtonDown (HELE hEle,UINT nFlags, POINT *pPt,BOOL *pbHandled);
            int OnRButtonUp(HELE hEle,UINT nFlags, POINT *pPt,BOOL *pbHandled);
            int OnLButtonDBClick(HELE hEle,UINT nFlags, POINT *pPt,BOOL *pbHandled);
            int OnRButtonDBClick(HELE hEle,UINT nFlags, POINT *pPt,BOOL *pbHandled);
            int OnEleXCTimer(HELE hEle,UINT nTimerID,BOOL *pbHandled);
            int OnSetFocus(HELE hEle,BOOL *pbHandled);
            int OnKillFocus(HELE hEle,BOOL *pbHandled);
            int OnDestroy(HELE hEle,BOOL *pbHandled);
            int OnDestroyeEnd(HELE hEle,BOOL *pbHandled);
            int OnSize(HELE hEle,int nFlags, BOOL *pbHandled);
            int OnShow(HELE hEle,BOOL bShow,BOOL *pbHandled);
            int OnSetFont(HELE hEle,BOOL *pbHandled);
            int OnEventKeyDown(HELE hEle,WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnEventKeyUp(HELE hEle,WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnEventChar(HELE hEle,WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnSetCapture(HELE hEle,BOOL *pbHandled);
            int OnKillCapture(HELE hEle,BOOL *pbHandled);
            int OnSetCursor(HELE hEle,WPARAM wParam,LPARAM lParam,BOOL *pbHandled);
            int OnMenuPopup(HELE hEle,HMENUX hMenu, BOOL *pbHandled);
            int OnMenuPopupWnd(HELE hEle,HMENUX hMenu,menu_popupWnd_* pInfo,BOOL *pbHandled);
            int OnMenuSelect(HELE hEle,int nItem,BOOL *pbHandled);
            int OnMenuDrawBackground(HELE hEle,HDRAW hDraw,menu_drawBackground_ *pInfo,BOOL *pbHandled);
            int OnMenuDrawItem(HELE hEle,HDRAW hDraw,menu_drawItem_* pInfo,BOOL *pbHandled);
            int OnMenuExit(HELE hEle,BOOL *pbHandled);
            int OnDropFiles(HELE hEle,HDROP hDropInfo, BOOL *pbHandled);
            int OnAdjustLayoutEnd(HELE hEle,int nFlags, UINT nAdjustNo, BOOL *pbHandled);
            int OnTooltipPopup(HELE hEle,HWINDOW hWindow,const wchar_t* pString, BOOL *pbHandled);

public:
    INT rg_YuanSu_ChuLiGuoCheng (INT rg_YuanSuGouBing6, INT rg_ShiJianLeiXing8, INT rg_FuJiaZhiYi, INT rg_FuJiaZhiEr, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie42);
    INT rg_YuanSu_HuiZhi (INT rg_YuanSuGouBing7, rg_XuanCaiHuiTu& rg_KaiShiHuiTu4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie43);
    INT rg_YuanSu_HuiZhiWanCheng (INT rg_YuanSuGouBing8, rg_XuanCaiHuiTu& rg_KaiShiHuiTu5, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie44);
    INT rg_YuanSu_HuiZhiGunDongShiTu (INT rg_YuanSuGouBing9, rg_XuanCaiHuiTu& rg_KaiShiHuiTu6, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie45);
    INT rg_YuanSu_ShuBiaoYiDong (INT rg_YuanSuGouBing10, INT rg_YuanSuBiaoZhi, rg_ZuoBiao_xc& rg_YuanSuZuoBiao, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie46);
    INT rg_YuanSu_ShuBiaoJinRu (INT rg_YuanSuGouBing11, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie47);
    INT rg_YuanSu_ShuBiaoXuanTing (INT rg_YuanSuGouBing12, INT rg_YuanSuBiaoZhi1, rg_ZuoBiao_xc& rg_YuanSuZuoBiao1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie48);
    INT rg_YuanSu_ShuBiaoLiKai (INT rg_YuanSuGouBing13, INT rg_TingLiuYuanSuGouBing, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie49);
    INT rg_YuanSu_ShuBiaoGunLunGunDong (INT rg_YuanSuGouBing14, INT rg_YuanSuBiaoZhi2, rg_ZuoBiao_xc& rg_YuanSuZuoBiao2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie50);
    INT rg_YuanSu_ShuBiaoZuoJianAnXia (INT rg_YuanSuGouBing15, INT rg_YuanSuBiaoZhi3, rg_ZuoBiao_xc& rg_YuanSuZuoBiao3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie51);
    INT rg_YuanSu_ShuBiaoZuoJianDanQi (INT rg_YuanSuGouBing16, INT rg_YuanSuBiaoZhi4, rg_ZuoBiao_xc& rg_YuanSuZuoBiao4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie52);
    INT rg_YuanSu_ShuBiaoYouJianAnXia (INT rg_YuanSuGouBing17, INT rg_YuanSuBiaoZhi5, rg_ZuoBiao_xc& rg_YuanSuZuoBiao5, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie53);
    INT rg_YuanSu_ShuBiaoYouJianDanQi (INT rg_YuanSuGouBing18, INT rg_YuanSuBiaoZhi6, rg_ZuoBiao_xc& rg_YuanSuZuoBiao6, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie54);
    INT rg_YuanSu_ShuBiaoZuoJianShuangJi (INT rg_YuanSuGouBing19, INT rg_YuanSuBiaoZhi7, rg_ZuoBiao_xc& rg_YuanSuZuoBiao7, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie55);
    INT rg_YuanSu_ShuBiaoYouJianShuangJi (INT rg_YuanSuGouBing20, INT rg_YuanSuBiaoZhi8, rg_ZuoBiao_xc& rg_YuanSuZuoBiao8, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie56);
    INT rg_YuanSu_DingShiQiXuanCai (INT rg_YuanSuGouBing21, INT rg_ShiZhongID2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie57);
    INT rg_YuanSu_HuoQuJiaoDian (INT rg_YuanSuGouBing22, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie58);
    INT rg_YuanSu_ShiQuJiaoDian (INT rg_YuanSuGouBing23, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie59);
    INT rg_YuanSu_XiaoHui (INT rg_YuanSuGouBing24, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie60);
    INT rg_YuanSu_XiaoHuiWanCheng (INT rg_YuanSuGouBing25, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie61);
    INT rg_YuanSu_DaXiaoGaiBian (INT rg_YuanSuGouBing26, INT rg_BiaoShi19, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie62);
    INT rg_YuanSu_XianShi (INT rg_YuanSuGouBing27, BOOL rg_XianShiYinCang, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie63);
    INT rg_YuanSu_ZhiZiTi (INT rg_YuanSuGouBing28, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie64);
    INT rg_YuanSu_AnJianAnXia (INT rg_YuanSuGouBing29, INT rg_FuJiaZhiYi1, INT rg_FuJiaZhiEr1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie65);
    INT rg_YuanSu_AnJianDanQi (INT rg_YuanSuGouBing30, INT rg_FuJiaZhiYi2, INT rg_FuJiaZhiEr2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie66);
    INT rg_YuanSu_ShuRuZiFu (INT rg_YuanSuGouBing31, INT rg_FuJiaZhiYi3, INT rg_FuJiaZhiEr3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie67);
    INT rg_YuanSu_ZhiShuBiaoBuHuo (INT rg_YuanSuGouBing32, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie68);
    INT rg_YuanSu_ShiQuShuBiaoBuHuo (INT rg_YuanSuGouBing33, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie69);
    INT rg_YuanSu_ZhiShuBiaoGuangBiao (INT rg_YuanSuGouBing34, INT rg_FuJiaZhiYi4, INT rg_FuJiaZhiEr4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie70);
    INT rg_YuanSu_CaiChanDanChu (INT rg_YuanSuGouBing35, INT rg_CaiChanGouBing2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie71);
    INT rg_YuanSu_CaiChanDanChuChuangKou (INT rg_YuanSuGouBing36, INT rg_CaiChanGouBing3, rg_CaiChan_DanChuChuangKouJieGou& rg_ChuangKouXinXi, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie72);
    INT rg_YuanSu_CaiChanXiangXuanZe (INT rg_YuanSuGouBing37, INT rg_CaiChanID1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie73);
    INT rg_YuanSu_CaiChanHuiZhiBeiJing (INT rg_YuanSuGouBing38, rg_XuanCaiHuiTu& rg_KaiShiHuiTu7, rg_CaiChan_HuiZhiBeiJingJieGou& rg_BeiJingJieGou1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie74);
    INT rg_YuanSu_CaiChanXiangHuiZhi (INT rg_YuanSuGouBing39, rg_XuanCaiHuiTu& rg_KaiShiHuiTu8, rg_CaiChan_HuiZhiXiangJieGou& rg_XiangJieGou1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie75);
    INT rg_YuanSu_CaiChanTuiChu (INT rg_YuanSuGouBing40, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie76);
    INT rg_YuanSu_WenJianTuoRu (INT rg_YuanSuGouBing41, rg_volcano_base::rg_WenBenShuZuLei& rg_WenJianShuZu1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie77);
    INT rg_YuanSu_DiaoZhengBuJuWanCheng (INT rg_YuanSuGouBing42, INT rg_BiaoShi20, INT rg_nAdjustNo, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie78);
    INT rg_YuanSu_DanChuGongJuDiShi (INT rg_YuanSuGouBing43, INT rg_ChuangKouGouBing49, CVolString& rg_WenBenNeiRong, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie79);
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing9);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing10);
    virtual void rg_HuiZhi1 (rg_XuanCaiHuiTu& rg_HuiTu1);
    virtual INT rg_QuZhuangTai ();
    virtual BOOL rg_ShiFouQiYong34 ();
    inline_ XEleBase () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XEleBase_YuanSu_ChuLiGuoCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_HuiZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_HuiZhiWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_HuiZhiGunDongShiTu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoYiDong (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoJinRu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoXuanTing (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoLiKai (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoGunLunGunDong (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoZuoJianAnXia (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoZuoJianDanQi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoYouJianAnXia (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoYouJianDanQi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoZuoJianShuangJi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuBiaoYouJianShuangJi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_DingShiQiXuanCai (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_HuoQuJiaoDian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShiQuJiaoDian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_XiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_XiaoHuiWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_DaXiaoGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_XianShi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ZhiZiTi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_AnJianAnXia (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_AnJianDanQi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShuRuZiFu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ZhiShuBiaoBuHuo (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ShiQuShuBiaoBuHuo (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_ZhiShuBiaoGuangBiao (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_CaiChanDanChu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_CaiChanDanChuChuangKou (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_CaiChanXiangXuanZe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_CaiChanHuiZhiBeiJing (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_CaiChanXiangHuiZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_CaiChanTuiChu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_WenJianTuoRu (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_DiaoZhengBuJuWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XEleBase_YuanSu_DanChuGongJuDiShi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_44;
    CVolEventReceiver rw_45;
    CVolEventReceiver rw_46;
    CVolEventReceiver rw_47;
    CVolEventReceiver rw_48;
    CVolEventReceiver rw_49;
    CVolEventReceiver rw_50;
    CVolEventReceiver rw_51;
    CVolEventReceiver rw_52;
    CVolEventReceiver rw_53;
    CVolEventReceiver rw_54;
    CVolEventReceiver rw_55;
    CVolEventReceiver rw_56;
    CVolEventReceiver rw_57;
    CVolEventReceiver rw_58;
    CVolEventReceiver rw_59;
    CVolEventReceiver rw_60;
    CVolEventReceiver rw_61;
    CVolEventReceiver rw_62;
    CVolEventReceiver rw_63;
    CVolEventReceiver rw_64;
    CVolEventReceiver rw_65;
    CVolEventReceiver rw_66;
    CVolEventReceiver rw_67;
    CVolEventReceiver rw_68;
    CVolEventReceiver rw_69;
    CVolEventReceiver rw_70;
    CVolEventReceiver rw_71;
    CVolEventReceiver rw_72;
    CVolEventReceiver rw_73;
    CVolEventReceiver rw_74;
    CVolEventReceiver rw_75;
    CVolEventReceiver rw_76;
    CVolEventReceiver rw_77;
    CVolEventReceiver rw_78;
    CVolEventReceiver rw_79;
    CVolEventReceiver rw_80;
    CVolEventReceiver rw_81;
};

}

#endif  //__VCLS_RG_XC_GUI_XELEBASE_H__
