
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_JICHUYUANSU_H__
#define __VCLS_RG_XC_GUI_RG_JICHUYUANSU_H__

namespace rg_xc_gui
{

class rg_JiChuYuanSu : public XEleBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_JiChuYuanSu)

public:
    virtual INT rg_ChuangJian6 (INT rg_ZuoBian32, INT rg_DingBian32, INT rg_KuanDu30, INT rg_GaoDu30, INT rg_FuGouBing4);
    inline_ rg_JiChuYuanSu () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_JICHUYUANSU_H__
