
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_XIAOSHULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_XIAOSHULEI_H__

namespace rg_volcano_base
{

class rg_XiaoShuLei : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_XiaoShuLei)

public:
    virtual void* GetDataPtr () override  { return &rg_value7; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_value7); }

public:
    rg_XiaoShuLei ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    DOUBLE rg_value7;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_XIAOSHULEI_H__
