
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_XWND_H__
#define __VCLS_RG_XC_GUI_XWND_H__

namespace rg_xc_gui
{

class XWnd : public WinBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, XWnd)

public:
    inline_ XWnd () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_XWND_H__
