
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAILIEBIAO_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAILIEBIAO_H__

namespace rg_xc_gui
{

class rg_XuanCaiLieBiao : public rg_XuanCaiGunDongShiTu
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiLieBiao)

public:
           int OnListTemplateCreate(HELE hEle,list_item_* pItem,int nFlag, BOOL *pbHandled);
           int OnListTemplateCreateEnd(HELE hEle,list_item_* pItem, int nFlag, BOOL *pbHandled);
           int OnListTemplateDestroy(HELE hEle,list_item_* pItem, int nFlag, BOOL *pbHandled);
           int OnListDrawItem(HELE hEle,HDRAW hDraw,list_item_* pItem,BOOL *pbHandled);
           int OnListSelect(HELE hEle,int iItem,BOOL *pbHandled);
           int OnListHeaderDrawItem(HELE hEle,HDRAW hDraw, list_header_item_* pItem, BOOL *pbHandled);
           int OnListHeaderClick(HELE hEle,int iItem, BOOL *pbHandled);
           int OnListHeaderItemWidthChange(HELE hEle,int iItem, int nWidth, BOOL *pbHandled);
           int OnListHeaderTemplateCreate(HELE hEle,list_header_item_* pItem,BOOL *pbHandled);
           int OnListHeaderTemplateCreateEnd(HELE hEle,list_header_item_* pItem,BOOL *pbHandled);
           int OnListHeaderTemplateDestroy(HELE hEle,list_header_item_* pItem,BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing19);
    INT rg_LieBiao_XiangMoBanChuangJian (INT rg_LieBiaoGouBing, rg_LieBiao_XiangJieGou& rg_XiangXinXiJieGou, INT rg_ZhuangTaiBiaoShi, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie87);
    INT rg_LieBiao_XiangMoBanChuangJianWanCheng (INT rg_LieBiaoGouBing1, rg_LieBiao_XiangJieGou& rg_XiangXinXiJieGou1, INT rg_ZhuangTaiBiaoShi1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie88);
    INT rg_LieBiao_XiangMoBanXiaoHui (INT rg_LieBiaoGouBing2, rg_LieBiao_XiangJieGou& rg_XiangXinXiJieGou2, INT rg_ZhuangTaiBiaoShi2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie89);
    INT rg_LieBiao_XiangHuiZhi (INT rg_LieBiaoGouBing3, rg_XuanCaiHuiTu& rg_KaiShiHuiTu10, rg_LieBiao_XiangJieGou& rg_XiangXinXiJieGou3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie90);
    INT rg_LieBiao_XiangXuanZe (INT rg_LieBiaoGouBing4, INT rg_XiangSuoYin20, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie91);
    INT rg_LieBiaoTou_XiangHuiZhi (INT rg_LieBiaoGouBing5, rg_XuanCaiHuiTu& rg_KaiShiHuiTu11, rg_LieBiao_TouXiangJieGou& rg_XiangJieGou3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie92);
    INT rg_LieBiaoTou_XiangDianJi (INT rg_LieBiaoGouBing6, INT rg_SuoYin2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie93);
    INT rg_LieBiaoTou_XiangKuanDuGaiBian (INT rg_LieBiaoGouBing7, INT rg_SuoYin3, INT rg_KuanDu38, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie94);
    INT rg_LieBiaoTou_XiangMoBanChuangJian (INT rg_LieBiaoGouBing8, rg_LieBiao_TouXiangJieGou& rg_TouXiangJieGou, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie95);
    INT rg_LieBiaoTou_XiangMoBanChuangJianWanCheng (INT rg_LieBiaoGouBing9, rg_LieBiao_TouXiangJieGou& rg_TouXiangJieGou1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie96);
    INT rg_LieBiaoTou_XiangMoBanXiaoHui (INT rg_LieBiaoGouBing10, rg_LieBiao_TouXiangJieGou& rg_TouXiangJieGou2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie97);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing20);
    virtual INT rg_ChuangJian9 (INT rg_ZuoBian39, INT rg_DingBian39, INT rg_KuanDu39, INT rg_GaoDu37, INT rg_FuGouBing13);
    inline_ rg_XuanCaiLieBiao () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiLieBiao_LieBiao_XiangMoBanChuangJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiao_XiangMoBanChuangJianWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiao_XiangMoBanXiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiao_XiangHuiZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiao_XiangXuanZe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiaoTou_XiangHuiZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiaoTou_XiangDianJi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiaoTou_XiangKuanDuGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiaoTou_XiangMoBanChuangJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiaoTou_XiangMoBanChuangJianWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiao_LieBiaoTou_XiangMoBanXiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_89;
    CVolEventReceiver rw_90;
    CVolEventReceiver rw_91;
    CVolEventReceiver rw_92;
    CVolEventReceiver rw_93;
    CVolEventReceiver rw_94;
    CVolEventReceiver rw_95;
    CVolEventReceiver rw_96;
    CVolEventReceiver rw_97;
    CVolEventReceiver rw_98;
    CVolEventReceiver rw_99;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAILIEBIAO_H__
