
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_JIEGOUJICHULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_JIEGOUJICHULEI_H__

namespace rg_volcano_base
{

class rg_JieGouJiChuLei : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_JieGouJiChuLei)

public:
    inline_ rg_JieGouJiChuLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_JIEGOUJICHULEI_H__
