
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_YUANSUSHIJIAN_H__
#define __VCLS_RG_XC_GUI_RG_YUANSUSHIJIAN_H__

namespace rg_xc_gui
{

class rg_YuanSuShiJian : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_YuanSuShiJian)

public:
    inline_ rg_YuanSuShiJian () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static const INT rg_ChuLiGuoCheng;
    static const INT rg_HuiZhiWanCheng;
    static const INT rg_HuiZhiGunDongShiTu;
    static const INT rg_ShuBiaoYiDong;
    static const INT rg_ShuBiaoJinRu;
    static const INT rg_ShuBiaoXuanTing;
    static const INT rg_ShuBiaoLiKai;
    static const INT rg_ShuBiaoGunLunGunDong;
    static const INT rg_ShuBiaoZuoJianAnXia;
    static const INT rg_ShuBiaoZuoJianDanQi;
    static const INT rg_ShuBiaoYouJianAnXia;
    static const INT rg_ShuBiaoYouJianDanQi;
    static const INT rg_ShuBiaoZuoJianShuangJi;
    static const INT rg_ShuBiaoYouJianShuangJi;
    static const INT rg_DingShiQiXuanCai;
    static const INT rg_BuJuDiaoZhengWanBi;
    static const INT rg_HuoQuJiaoDian1;
    static const INT rg_ShiQuJiaoDian1;
    static const INT rg_XiaoHui4;
    static const INT rg_button_DianJi1;
    static const INT rg_button_XuanZhong1;
    static const INT rg_DaXiaoGaiBian;
    static const INT rg_XianShi2;
    static const INT rg_ZhiZiTi1;
    static const INT rg_AnJianAnXia;
    static const INT rg_AnJianDanQi;
    static const INT rg_ShuRuZiFu;
    static const INT rg_XiaoHuiWanCheng;
    static const INT rg_ZhiShuBiaoBuHuo1;
    static const INT rg_ShiQuShuBiaoBuHuo;
    static const INT rg_ZhiShuBiaoGuangBiao;
    static const INT rg_GunDongShiTu_ShuiPingGunDong1;
    static const INT rg_GunDongShiTu_ChuiZhiGunDong1;
    static const INT rg_scroll_bar_GunDong1;
    static const INT rg_CaiChan_DanChu;
    static const INT rg_CaiChan_DanChuChuangKou;
    static const INT rg_CaiChan_XiangXuanZe;
    static const INT rg_CaiChan_HuiZhiBeiJing;
    static const INT rg_CaiChan_XiangHuiZhi;
    static const INT rg_CaiChan_TuiChu;
    static const INT rg_HuaDongTiao_WeiZhiGaiBian1;
    static const INT rg_process_bar_WeiZhiGaiBian1;
    static const INT rg_combo_box_XiangXuanZe1;
    static const INT rg_combo_box_DanChuLieBiao1;
    static const INT rg_combo_box_TuiChuLieBiao1;
    static const INT rg_combo_box_XiangXuanZeWanCheng1;
    static const INT rg_list_box_XiangMoBanChuangJian1;
    static const INT rg_list_box_XiangMoBanChuangJianWanCheng1;
    static const INT rg_list_box_XiangMoBanXiaoHui1;
    static const INT rg_list_box_XiangHuiZhi1;
    static const INT rg_list_box_XiangXuanZe1;
    static const INT rg_LieBiao_XiangMoBanChuangJian1;
    static const INT rg_LieBiao_XiangMoBanChuangJianWanCheng1;
    static const INT rg_LieBiao_XiangMoBanXiaoHui1;
    static const INT rg_LieBiao_XiangHuiZhi1;
    static const INT rg_LieBiao_XiangXuanZe1;
    static const INT rg_LieBiaoTou_XiangHuiZhi1;
    static const INT rg_LieBiaoTou_XiangDianJi1;
    static const INT rg_LieBiaoTou_XiangKuanDuGaiBian1;
    static const INT rg_LieBiaoTou_XiangMoBanChuangJian1;
    static const INT rg_LieBiaoTou_XiangMoBanChuangJianWanCheng1;
    static const INT rg_LieBiaoTou_XiangMoBanXiaoHui1;
    static const INT rg_LieBiaoShu_XiangMoBanChuangJian1;
    static const INT rg_LieBiaoShu_XiangMoBanChuangJianWanCheng1;
    static const INT rg_LieBiaoShu_XiangMoBanXiaoHui1;
    static const INT rg_LieBiaoShu_XiangHuiZhi1;
    static const INT rg_LieBiaoShu_XiangXuanZe1;
    static const INT rg_LieBiaoShu_XiangZhanKai1;
    static const INT rg_LieBiaoShu_XiangZhengZaiTuoDong1;
    static const INT rg_LieBiaoShu_XiangTuoDongWanBi1;
    static const INT rg_LieBiaoShiTu_XiangMoBanChuangJian1;
    static const INT rg_LieBiaoShiTu_XiangMoBanChuangJianWanCheng1;
    static const INT rg_LieBiaoShiTu_XiangMoBanXiaoHui1;
    static const INT rg_LieBiaoShiTu_XiangHuiZhi1;
    static const INT rg_LieBiaoShiTu_XiangXuanZe1;
    static const INT rg_LieBiaoShiTu_XiangZhanKai1;
    static const INT rg_ShuXingKuang_XiangZhiGaiBian1;
    static const INT rg_ShuXingKuang_XiangSheZhi1;
    static const INT rg_ShuXingKuang_XiangXuanZe1;
    static const INT rg_ShuXingKuang_XiangDiaoZhengZuoBiao1;
    static const INT rg_ShuXingKuang_XiangXiaoHui1;
    static const INT rg_ShuXingKuang_XiangZhanKai1;
    static const INT rg_edit_box_ZhiNeiRong1;
    static const INT rg_edit_box_NeiRongGengGai;
    static const INT rg_edit_box_WeiZhiGaiBian1;
    static const INT rg_edit_box_YangShiGaiBian1;
    static const INT rg_edit_box_HuiCheTABDuiJi1;
    static const INT rg_edit_box_JiaoHuanHang1;
    static const INT rg_DaiMaKuang_DuoHangNeiRongGaiBian1;
    static const INT rg_DaiMaKuang_SheZhiDuanDian1;
    static const INT rg_DaiMaKuang_YiChuDuanDian1;
    static const INT rg_DaiMaKuang_DuanDianGaiBian1;
    static const INT rg_DaiMaKuang_ZiDongXuanZe1;
    static const INT rg_TabTiao_XiangXuanZe1;
    static const INT rg_TabTiao_XiangShanChu1;
    static const INT rg_YueLiKuang_RiJiGaiBian1;
    static const INT rg_RiJiKuang_NeiRongGaiBian1;
    static const INT rg_RiJiKuang_DanChuYueLi1;
    static const INT rg_RiJiKuang_TuiChuYueLi1;
    static const INT rg_DanChuGongJuDiShi1;
    static const INT rg_WenJianTuoRu;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_YUANSUSHIJIAN_H__
