
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_BIANZHENGSHUCANKAOSHUZULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_BIANZHENGSHUCANKAOSHUZULEI_H__

namespace rg_volcano_base
{

class rg_BianZhengShuCanKaoShuZuLei : public rg_KuoZhanDuiXiangLei
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_BianZhengShuCanKaoShuZuLei)

protected:
    inline_ void _OnInitExtra ()  {  m_pRefObject = new CRefObjectWithData<CMArray<INT>>; }
    inline_ void _OnCleanupExtra ()  { if (m_pRefObject != NULL)  m_pRefObject->Release (); }
    inline_ void _CopySelfFromExtra (const rg_BianZhengShuCanKaoShuZuLei& objCopyFrom)  { SetRefObject (objCopyFrom.m_pRefObject); }
    inline_ BOOL _IsSelfEqualExtra (const rg_BianZhengShuCanKaoShuZuLei& objCompare) const  { return (m_pRefObject == objCompare.m_pRefObject); }
    CRefObject* m_pRefObject;
public:
    void SetRefObject (CRefObject* pRefObject);
    void TakeOverNewRefObject (CRefObject* pNewRefObject);
    inline_ CRefObject* GetRefObject ()  {  return m_pRefObject;  }
public:
    inline_ CMArray<INT>& data ()  { return ((CRefObjectWithData<CMArray<INT>>*)m_pRefObject)->m_data; }
    inline_ CMArray<INT>* pdata ()  { return &((CRefObjectWithData<CMArray<INT>>*)m_pRefObject)->m_data; }

public:
    virtual void GetDumpString (CVolString& rg_ZhanShiNeiRong13, INT rg_ZuiDaZhanShiShuJuCheCun13);
    virtual void LoadFromStream (CVolBaseInputStream& rg_LiuDuiXiang26);
    virtual void SaveIntoStream (CVolBaseOutputStream& rg_LiuDuiXiang27);
    rg_BianZhengShuCanKaoShuZuLei ();
    void _VolObjectInitMembers ();
    virtual ~rg_BianZhengShuCanKaoShuZuLei ();
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_BIANZHENGSHUCANKAOSHUZULEI_H__
