
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_DUIXIANGLEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_DUIXIANGLEI_H__

namespace rg_volcano_base
{

class rg_DuiXiangLei : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_DuiXiangLei)

public:
    inline_ rg_DuiXiangLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_DUIXIANGLEI_H__
