
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_MOTAICHUANGKOU_H__
#define __VCLS_RG_XC_GUI_RG_MOTAICHUANGKOU_H__

namespace rg_xc_gui
{

class rg_MoTaiChuangKou : public WinBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_MoTaiChuangKou)

public:
    inline_ rg_MoTaiChuangKou () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_MOTAICHUANGKOU_H__
