
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_ZIJIELEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_ZIJIELEI_H__

namespace rg_volcano_base
{

class rg_ZiJieLei : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_ZiJieLei)

public:
    virtual void* GetDataPtr () override  { return &rg_value; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_value); }

public:
    rg_ZiJieLei ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    S_BYTE rg_value;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_ZIJIELEI_H__
