
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIBIANJIKUANG_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIBIANJIKUANG_H__

namespace rg_xc_gui
{

class rg_XuanCaiBianJiKuang : public rg_XuanCaiGunDongShiTu
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiBianJiKuang)

public:
           int OnEditSet(HELE hEle,BOOL *pbHandled);
           int OnEditChanged(HELE hEle,BOOL *pbHandled);
           int OnEditPosChanged(HELE hEle,int iPos, BOOL *pbHandled);
           int OnEditStyleChanged(HELE hEle,int iStyle, BOOL *pbHandled);
           int OnEditEnterGetTabAlign(HELE hEle,BOOL *pbHandled) ;
           int OnEditSwpaRow(HELE hEle,int iRow, int bArrowUp,BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing25);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing26);
    INT rg_edit_box_ZhiNeiRong (INT rg_BianJiKuangGouBing, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie112);
    INT rg_edit_box_NeiRongGaiBian (INT rg_BianJiKuangGouBing1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie113);
    INT rg_edit_box_WeiZhiGaiBian (INT rg_BianJiKuangGouBing2, INT rg_WeiZhi16, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie114);
    INT rg_edit_box_YangShiGaiBian (INT rg_BianJiKuangGouBing3, INT rg_YangShi3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie115);
    INT rg_edit_box_HuiCheTABDuiJi (INT rg_BianJiKuangGouBing4, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie116);
    INT rg_edit_box_JiaoHuanHang (INT rg_BianJiKuangGouBing5, INT rg_KaiShiHang, INT rg_JianDaiMa, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie117);
    virtual INT rg_ChuangJian9 (INT rg_ZuoBian45, INT rg_DingBian45, INT rg_KuanDu50, INT rg_GaoDu51, INT rg_FuGouBing19);
    inline_ rg_XuanCaiBianJiKuang () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiBianJiKuang_edit_box_ZhiNeiRong (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiBianJiKuang_edit_box_NeiRongGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiBianJiKuang_edit_box_WeiZhiGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiBianJiKuang_edit_box_YangShiGaiBian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiBianJiKuang_edit_box_HuiCheTABDuiJi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiBianJiKuang_edit_box_JiaoHuanHang (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_114;
    CVolEventReceiver rw_115;
    CVolEventReceiver rw_116;
    CVolEventReceiver rw_117;
    CVolEventReceiver rw_118;
    CVolEventReceiver rw_119;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIBIANJIKUANG_H__
