
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_WIDGETUI_H__
#define __VCLS_RG_XC_GUI_WIDGETUI_H__

namespace rg_xc_gui
{

class widgetUI : public xcguibase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, widgetUI)

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    inline_ widgetUI () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_WIDGETUI_H__
