
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_CHUANGKOUSHIJIAN_H__
#define __VCLS_RG_XC_GUI_RG_CHUANGKOUSHIJIAN_H__

namespace rg_xc_gui
{

class rg_ChuangKouShiJian : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_ChuangKouShiJian)

public:
    inline_ rg_ChuangKouShiJian () { }
    inline_ void _VolObjectInitMembers () { }

public:
    static const INT rg_KuangJiaChuangKouMaTouDanChuChuangGe;
    static const INT rg_FuDongChuangKouTuoDong;
    static const INT rg_ChuangGeXianShiYinCang;
    static const INT rg_ZiDingYiShiJian;
    static const INT rg_ChuLiGuoCheng1;
    static const INT rg_HuiZhiWanChengBingYiXianShi;
    static const INT rg_DingShiQiXuanCai1;
    static const INT rg_CaiChanDanChu;
    static const INT rg_CaiChanDanChuChuangKou;
    static const INT rg_CaiChanXuanZe;
    static const INT rg_CaiChanTuiChu;
    static const INT rg_HuiZhiCaiChanBeiJing;
    static const INT rg_HuiZhiCaiChanXiang;
    static const INT rg_ChuangGeFuDong;
    static const INT rg_HuiZhiWanCheng1;
    static const INT rg_TuoPan;
    static const INT rg_XiaoHui5;
    static const INT rg_CheCunGaiBian;
    static const INT rg_HuoDeJiaoDian;
    static const INT rg_ShiQuJiaoDian2;
    static const INT rg_HuiZhi3;
    static const INT rg_GuanBi6;
    static const INT rg_SheZhiShuBiaoGuangBiao;
    static const INT rg_WeiZhiGaiBian;
    static const INT rg_AnJianAnXia1;
    static const INT rg_AnJianDanQi1;
    static const INT rg_ShuRuZiFu1;
    static const INT rg_DingShiQi;
    static const INT rg_ShuBiaoYiDong1;
    static const INT rg_ShuBiaoZuoJianAnXia1;
    static const INT rg_ShuBiaoZuoJianDanQi1;
    static const INT rg_ShuBiaoZuoJianShuangJi1;
    static const INT rg_ShuBiaoYouJianAnXia1;
    static const INT rg_ShuBiaoYouJianDanQi1;
    static const INT rg_ShuBiaoYouJianShuangJi1;
    static const INT rg_ShuBiaoGunLunGunDong1;
    static const INT rg_ShuBiaoBuHuoGaiBian;
    static const INT rg_WenJianTuoFang;
    static const INT rg_ShuBiaoJinRu1;
    static const INT rg_ShuBiaoLiKai1;
    static const INT rg_JiTongAnJianAnXia;
    static const INT rg_HuoDeJiaoDian_YuanSu;
    static const INT rg_ZhuShiTuZuoBiaoGaiBian;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_CHUANGKOUSHIJIAN_H__
