
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAICHUANGGE_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAICHUANGGE_H__

namespace rg_xc_gui
{

class rg_XuanCaiChuangGe : public XEleBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiChuangGe)

public:
    virtual void rg_HuiZhi1 (rg_XuanCaiHuiTu& rg_hDraw);
    virtual BOOL rg_ShiFouXianShi2 ();
    inline_ rg_XuanCaiChuangGe () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAICHUANGGE_H__
