
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XINGZHUANGJUXING_H__
#define __VCLS_RG_XC_GUI_RG_XINGZHUANGJUXING_H__

namespace rg_xc_gui
{

class rg_XingZhuangJuXing : public rg_XingZhuangJiLei
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XingZhuangJuXing)

public:
    inline_ rg_XingZhuangJuXing () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XINGZHUANGJUXING_H__
