
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIBUJU_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIBUJU_H__

namespace rg_xc_gui
{

class rg_XuanCaiBuJu : public XEleBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiBuJu)

public:
    virtual INT rg_ChuangJian8 (INT rg_ZuoBian35, INT rg_DingBian35, INT rg_KuanDu33, INT rg_GaoDu33, INT rg_FuGouBing7);
    inline_ rg_XuanCaiBuJu () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIBUJU_H__
