
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_CHANGZHENGSHULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_CHANGZHENGSHULEI_H__

namespace rg_volcano_base
{

class rg_ChangZhengShuLei : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_ChangZhengShuLei)

public:
    virtual void* GetDataPtr () override  { return &rg_value5; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_value5); }

public:
    rg_ChangZhengShuLei ();
    void _VolObjectInitMembers ();
    virtual void LoadFromStream (CVolBaseInputStream& stream) override;
    virtual void SaveIntoStream (CVolBaseOutputStream& stream) override;

public:
    INT64 rg_value5;
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_CHANGZHENGSHULEI_H__
