
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIKESHEJILEI_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIKESHEJILEI_H__

namespace rg_xc_gui
{

class rg_XuanCaiKeSheJiLei : public rg_volcano_base::rg_KeSheJiLei
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiKeSheJiLei)

public:
    BOOL rg_ChuangJian32 (INT rg_FuGouBing46, INT rg_FuJiaChuangKou12);
    virtual void rg_ChuangJianWanCheng1 ();
    inline_ rg_XuanCaiKeSheJiLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIKESHEJILEI_H__
