
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAICAICHANTIAO_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAICAICHANTIAO_H__

namespace rg_xc_gui
{

class rg_XuanCaiCaiChanTiao : public XEleBase
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiCaiChanTiao)

public:
    inline_ rg_XuanCaiCaiChanTiao () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAICAICHANTIAO_H__
