
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_WENBENSHUZULEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_WENBENSHUZULEI_H__

namespace rg_volcano_base
{

class rg_WenBenShuZuLei : public rg_KuoZhanDuiXiangLei
{
    DECLARE_VOL_CLASS (rg_volcano_base, rg_WenBenShuZuLei)

public:
    inline_ void _CopySelfFromExtra (const rg_WenBenShuZuLei& objCopyFrom)
    {
        m_aryData.Copy (objCopyFrom.m_aryData);
    }
    inline_ BOOL _IsSelfEqualExtra (const rg_WenBenShuZuLei& objCompare) const
    {
        return (BOOL)m_aryData.IsEqual (objCompare.m_aryData, FALSE);
    }
    inline_ CMStringArray& data ()
    {
        return m_aryData;
    }
    CMStringArray m_aryData;

public:
    virtual void GetDumpString (CVolString& rg_ZhanShiNeiRong18, INT rg_ZuiDaZhanShiShuJuCheCun18);
    virtual void LoadFromStream (CVolBaseInputStream& rg_LiuDuiXiang36);
    virtual void SaveIntoStream (CVolBaseOutputStream& rg_LiuDuiXiang37);
    inline_ rg_WenBenShuZuLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_WENBENSHUZULEI_H__
