
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIZUGEKUANG_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIZUGEKUANG_H__

namespace rg_xc_gui
{

class rg_XuanCaiZuGeKuang : public rg_XuanCaiBianJiKuang
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiZuGeKuang)

public:
           int OnComboBoxSelect(HELE hEle,int iItem,BOOL *pbHandled);
           int OnComboBoxSelectEnd(HELE hEle,int iItem,BOOL *pbHandled);
           int OnComboBoxPopupList(HELE hEle,HWINDOW hWindow,HELE hListBox,BOOL *pbHandled);
           int OnComboBoxExitList(HELE hEle,BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing29);
    INT rg_combo_box_XiangXuanZe (INT rg_ZuGeKuangGouBing, INT rg_XiangMuSuoYin, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie123);
    INT rg_combo_box_XiangXuanZeWanCheng (INT rg_ZuGeKuangGouBing1, INT rg_XiangMuSuoYin1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie124);
    INT rg_combo_box_DanChuLieBiao (INT rg_ZuGeKuangGouBing2, INT rg_ChuangKouGouBing50, INT rg_LieBiaoKuangGouBing5, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie125);
    INT rg_combo_box_TuiChuLieBiao (INT rg_ZuGeKuangGouBing3, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie126);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing30);
    virtual INT rg_ChuangJian9 (INT rg_ZuoBian48, INT rg_DingBian48, INT rg_KuanDu55, INT rg_GaoDu54, INT rg_FuGouBing22);
    virtual INT rg_QuZhuangTai ();
    inline_ rg_XuanCaiZuGeKuang () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiZuGeKuang_combo_box_XiangXuanZe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiZuGeKuang_combo_box_XiangXuanZeWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiZuGeKuang_combo_box_DanChuLieBiao (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiZuGeKuang_combo_box_TuiChuLieBiao (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_125;
    CVolEventReceiver rw_126;
    CVolEventReceiver rw_127;
    CVolEventReceiver rw_128;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIZUGEKUANG_H__
