
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAIWENBENLIANJIE_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAIWENBENLIANJIE_H__

namespace rg_xc_gui
{

class rg_XuanCaiWenBenLianJie : public xcann
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiWenBenLianJie)

public:
    virtual INT rg_ChuangJian7 (INT rg_ZuoBian34, INT rg_DingBian34, INT rg_KuanDu32, INT rg_GaoDu32, CVolString& rg_BiaoTi10, INT rg_FuGouBing6);
    inline_ rg_XuanCaiWenBenLianJie () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAIWENBENLIANJIE_H__
