
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_XC_GUI_RG_XUANCAILIEBIAOSHU_H__
#define __VCLS_RG_XC_GUI_RG_XUANCAILIEBIAOSHU_H__

namespace rg_xc_gui
{

class rg_XuanCaiLieBiaoShu : public rg_XuanCaiGunDongShiTu
{
    DECLARE_EMPTY_VOL_CLASS (rg_xc_gui, rg_XuanCaiLieBiaoShu)

public:
           int OnTreeTemplateCreate(HELE hEle,tree_item_* pItem,int nFlag, BOOL *pbHandled);
           int OnTreeTemplateCreateEnd(HELE hEle,tree_item_* pItem, int nFlag, BOOL *pbHandled);
           int OnTreeTemplateDestroy(HELE hEle,tree_item_* pItem, int nFlag, BOOL *pbHandled);
           int OnTreeDrawItem(HELE hEle,HDRAW hDraw,tree_item_* pItem,BOOL *pbHandled);
           int OnTreeSelect(HELE hEle,int nItemID,BOOL *pbHandled);
           int OnTreeExpand(HELE hEle,int id,BOOL bExpand,BOOL *pbHandled);
           int OnTreeDragItemIng(HELE hEle,tree_drag_item_* pInfo, BOOL *pbHandled);
           int OnTreeDragItem(HELE hEle,tree_drag_item_* pInfo, BOOL *pbHandled);

public:
    virtual void rg_ZiDongZhuCeShiJian ();
    virtual void rg_ZhuCeShiJian1 (INT rg_ShiJianLeiXing23);
    INT rg_LieBiaoShu_XiangMoBanChuangJian (INT rg_LieBiaoShuGouBing, rg_LieBiaoShu_XiangJieGou& rg_XiangJieGou8, INT rg_ZhuangTaiBiaoShi6, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie104);
    INT rg_LieBiaoShu_XiangMoBanChuangJianWanCheng (INT rg_LieBiaoShuGouBing1, rg_LieBiaoShu_XiangJieGou& rg_XiangJieGou9, INT rg_ZhuangTaiBiaoShi7, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie105);
    INT rg_LieBiaoShu_XiangMoBanXiaoHui (INT rg_LieBiaoShuGouBing2, rg_LieBiaoShu_XiangJieGou& rg_XiangJieGou10, INT rg_ZhuangTaiBiaoShi8, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie106);
    INT rg_LieBiaoShu_XiangHuiZhi (INT rg_LieBiaoShuGouBing3, rg_XuanCaiHuiTu& rg_KaiShiHuiTu13, rg_LieBiaoShu_XiangJieGou& rg_XiangJieGou11, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie107);
    INT rg_LieBiaoShu_XiangXuanZe (INT rg_LieBiaoShuGouBing4, INT rg_XiangID2, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie108);
    INT rg_LieBiaoShu_XiangZhanKai (INT rg_LieBiaoShuGouBing5, INT rg_XiangID3, BOOL rg_ZhanKaiShouSu1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie109);
    INT rg_LieBiaoShu_XiangZhengZaiTuoDong (INT rg_LieBiaoShuGouBing6, rg_LieBiaoShu_XiangTuoDongJieGou& rg_TuoDongJieGou, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie110);
    INT rg_LieBiaoShu_XiangTuoDongWanBi (INT rg_LieBiaoShuGouBing7, rg_LieBiaoShu_XiangTuoDongJieGou& rg_TuoDongJieGou1, rg_volcano_base::rg_LuoJiXingLei& rg_ShiFouLanJie111);
    virtual void rg_YiChuShiJian1 (INT rg_ShiJianLeiXing24);
    virtual INT rg_ChuangJian9 (INT rg_ZuoBian43, INT rg_DingBian43, INT rg_KuanDu47, INT rg_GaoDu46, INT rg_FuGouBing17);
    inline_ rg_XuanCaiLieBiaoShu () { }
    inline_ void _VolObjectInitMembers () { }

public:
    void ra_XuanCaiLieBiaoShu_LieBiaoShu_XiangMoBanChuangJian (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShu_LieBiaoShu_XiangMoBanChuangJianWanCheng (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShu_LieBiaoShu_XiangMoBanXiaoHui (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShu_LieBiaoShu_XiangHuiZhi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShu_LieBiaoShu_XiangXuanZe (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShu_LieBiaoShu_XiangZhanKai (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShu_LieBiaoShu_XiangZhengZaiTuoDong (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_XuanCaiLieBiaoShu_LieBiaoShu_XiangTuoDongWanBi (VOID_FUNC fnReceiver, CVolEventObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_106;
    CVolEventReceiver rw_107;
    CVolEventReceiver rw_108;
    CVolEventReceiver rw_109;
    CVolEventReceiver rw_110;
    CVolEventReceiver rw_111;
    CVolEventReceiver rw_112;
    CVolEventReceiver rw_113;
};

}

#endif  //__VCLS_RG_XC_GUI_RG_XUANCAILIEBIAOSHU_H__
