
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_VOLCANO_BASE_RG_CHENGXUDIAOSHILEI_H__
#define __VCLS_RG_VOLCANO_BASE_RG_CHENGXUDIAOSHILEI_H__

namespace rg_volcano_base
{

class rg_ChengXuDiaoShiLei : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_volcano_base, rg_ChengXuDiaoShiLei)

public:
    static BOOL CALLBACK rg_ShiFouWeiDiaoShiBan ();
    inline_ rg_ChengXuDiaoShiLei () { }
    inline_ void _VolObjectInitMembers () { }
};

}

#endif  //__VCLS_RG_VOLCANO_BASE_RG_CHENGXUDIAOSHILEI_H__
