
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VOL_USER_APP_INFO_H__
#define __VOL_USER_APP_INFO_H__

#define _VOL_DEV_VERSION_NUMBER  22
#define _VOL_DEV_LANG_ID  2052
#define _VOL_DEV_CATEGORY  2

#define _T_VOL_USER_APP_NAME  _T ("火山应用程序")
#define _VOL_USER_APP_VERSION_NUMBER  1
#define _T_USER_APP_VERSION_NAME  _T ("")
#define _VOL_USER_APP_ICON_RES_ID  100

#endif  // __VOL_USER_APP_INFO_H__
