
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_volcano_base
{

BOOL rg_BianZhengShuShuZuLei::_IsSelfEqual (const rg_BianZhengShuShuZuLei& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_BianZhengShuShuZuLei::_CopySelfFrom (const rg_BianZhengShuShuZuLei& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

void rg_BianZhengShuShuZuLei::GetDumpString (CVolString& rg_ZhanShiNeiRong4, INT rg_ZuiDaZhanShiShuJuCheCun4)
{
    CMArray<INT>& ary = data ();
    if (rg_ZuiDaZhanShiShuJuCheCun4 == 0)
        rg_ZuiDaZhanShiShuJuCheCun4 = 64;
    const INT_P npCount = ary.GetCount ();
    const INT_P npDumpedCount = (rg_ZuiDaZhanShiShuJuCheCun4 < 0 ? npCount : MIN (npCount, rg_ZuiDaZhanShiShuJuCheCun4));
    if (npCount == npDumpedCount)
        rg_ZhanShiNeiRong4.AddFormatText (_T_ARY_ELEMENTS_DUMPED1_D, (INT)npCount);
    else
        rg_ZhanShiNeiRong4.AddFormatText (_T_ARY_ELEMENTS_DUMPED2_DDD, (INT)npCount, npDumpedCount, (INT)(npCount - npDumpedCount));
    for (INT_P npIndex = 0; npIndex < npDumpedCount; npIndex++)
        rg_ZhanShiNeiRong4.AddFormatText (_T ("\r\n%d. %s"), (INT)(npIndex + 1), CVolString (ary.GetAt (npIndex)).GetText ());
}

void rg_BianZhengShuShuZuLei::LoadFromStream (CVolBaseInputStream& rg_LiuDuiXiang8)
{
    data ().LoadFromStream (rg_LiuDuiXiang8);
}

void rg_BianZhengShuShuZuLei::SaveIntoStream (CVolBaseOutputStream& rg_LiuDuiXiang9)
{
    data ().SaveIntoStream (rg_LiuDuiXiang9);
}

rg_BianZhengShuCanKaoShuZuLei::rg_BianZhengShuCanKaoShuZuLei ()
{
    _VolObjectInitMembers ();
}

void rg_BianZhengShuCanKaoShuZuLei::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_BianZhengShuCanKaoShuZuLei::_IsSelfEqual (const rg_BianZhengShuCanKaoShuZuLei& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_BianZhengShuCanKaoShuZuLei::_CopySelfFrom (const rg_BianZhengShuCanKaoShuZuLei& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_BianZhengShuCanKaoShuZuLei::~rg_BianZhengShuCanKaoShuZuLei ()
{
    OnBeforeObjectCleanup ();
    _OnCleanupExtra ();
}
void rg_BianZhengShuCanKaoShuZuLei::SetRefObject (CRefObject* pRefObject)
{
    ASSERT_R_DATA_OR_NULL (pRefObject);
    if (pRefObject != NULL)  pRefObject->AddRef ();
    if (m_pRefObject != NULL)  m_pRefObject->Release ();
    m_pRefObject = pRefObject;
}
void rg_BianZhengShuCanKaoShuZuLei::TakeOverNewRefObject (CRefObject* pNewRefObject)
{
    ASSERT (pNewRefObject != m_pRefObject);
    ASSERT_R_DATA_OR_NULL (pNewRefObject);
    if (m_pRefObject != NULL)  m_pRefObject->Release ();
    m_pRefObject = pNewRefObject;
}

void rg_BianZhengShuCanKaoShuZuLei::GetDumpString (CVolString& rg_ZhanShiNeiRong13, INT rg_ZuiDaZhanShiShuJuCheCun13)
{
    CMArray<INT>& ary = data ();
    if (rg_ZuiDaZhanShiShuJuCheCun13 == 0)
        rg_ZuiDaZhanShiShuJuCheCun13 = 64;
    const INT_P npCount = ary.GetCount ();
    const INT_P npDumpedCount = (rg_ZuiDaZhanShiShuJuCheCun13 < 0 ? npCount : MIN (npCount, rg_ZuiDaZhanShiShuJuCheCun13));
    if (npCount == npDumpedCount)
        rg_ZhanShiNeiRong13.AddFormatText (_T_ARY_ELEMENTS_DUMPED1_D, (INT)npCount);
    else
        rg_ZhanShiNeiRong13.AddFormatText (_T_ARY_ELEMENTS_DUMPED2_DDD, (INT)npCount, npDumpedCount, (INT)(npCount - npDumpedCount));
    for (INT_P npIndex = 0; npIndex < npDumpedCount; npIndex++)
        rg_ZhanShiNeiRong13.AddFormatText (_T ("\r\n%d. %s"), (INT)(npIndex + 1), CVolString (ary.GetAt (npIndex)).GetText ());
}

void rg_BianZhengShuCanKaoShuZuLei::LoadFromStream (CVolBaseInputStream& rg_LiuDuiXiang26)
{
    data ().LoadFromStream (rg_LiuDuiXiang26);
}

void rg_BianZhengShuCanKaoShuZuLei::SaveIntoStream (CVolBaseOutputStream& rg_LiuDuiXiang27)
{
    data ().SaveIntoStream (rg_LiuDuiXiang27);
}

BOOL rg_WenBenShuZuLei::_IsSelfEqual (const rg_WenBenShuZuLei& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_WenBenShuZuLei::_CopySelfFrom (const rg_WenBenShuZuLei& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

void rg_WenBenShuZuLei::GetDumpString (CVolString& rg_ZhanShiNeiRong18, INT rg_ZuiDaZhanShiShuJuCheCun18)
{
    data ().GetDumpString (rg_ZhanShiNeiRong18, rg_ZuiDaZhanShiShuJuCheCun18);
}

void rg_WenBenShuZuLei::LoadFromStream (CVolBaseInputStream& rg_LiuDuiXiang36)
{
    data ().LoadFromStream (rg_LiuDuiXiang36);
}

void rg_WenBenShuZuLei::SaveIntoStream (CVolBaseOutputStream& rg_LiuDuiXiang37)
{
    data ().SaveIntoStream (rg_LiuDuiXiang37);
}

}
