
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_xc_gui
{

rg_ZuoBiao_xc::rg_ZuoBiao_xc ()
{
    _VolObjectInitMembers ();
}

void rg_ZuoBiao_xc::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_ZuoBiao_xc::_IsSelfEqual (const rg_ZuoBiao_xc& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_ZuoBiao_xc::_CopySelfFrom (const rg_ZuoBiao_xc& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_CheCun_xc::rg_CheCun_xc ()
{
    _VolObjectInitMembers ();
}

void rg_CheCun_xc::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_CheCun_xc::_IsSelfEqual (const rg_CheCun_xc& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_CheCun_xc::_CopySelfFrom (const rg_CheCun_xc& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_list_box_XiangJieGou::rg_list_box_XiangJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_list_box_XiangJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_list_box_XiangJieGou::_IsSelfEqual (const rg_list_box_XiangJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_list_box_XiangJieGou::_CopySelfFrom (const rg_list_box_XiangJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_CaiChan_HuiZhiBeiJingJieGou::rg_CaiChan_HuiZhiBeiJingJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_CaiChan_HuiZhiBeiJingJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_CaiChan_HuiZhiBeiJingJieGou::_IsSelfEqual (const rg_CaiChan_HuiZhiBeiJingJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_CaiChan_HuiZhiBeiJingJieGou::_CopySelfFrom (const rg_CaiChan_HuiZhiBeiJingJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_CaiChan_HuiZhiXiangJieGou::rg_CaiChan_HuiZhiXiangJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_CaiChan_HuiZhiXiangJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_CaiChan_HuiZhiXiangJieGou::_IsSelfEqual (const rg_CaiChan_HuiZhiXiangJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_CaiChan_HuiZhiXiangJieGou::_CopySelfFrom (const rg_CaiChan_HuiZhiXiangJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_CaiChan_DanChuChuangKouJieGou::rg_CaiChan_DanChuChuangKouJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_CaiChan_DanChuChuangKouJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_CaiChan_DanChuChuangKouJieGou::_IsSelfEqual (const rg_CaiChan_DanChuChuangKouJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_CaiChan_DanChuChuangKouJieGou::_CopySelfFrom (const rg_CaiChan_DanChuChuangKouJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_LieBiaoShu_XiangJieGou::rg_LieBiaoShu_XiangJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_LieBiaoShu_XiangJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_LieBiaoShu_XiangJieGou::_IsSelfEqual (const rg_LieBiaoShu_XiangJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_LieBiaoShu_XiangJieGou::_CopySelfFrom (const rg_LieBiaoShu_XiangJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_LieBiaoShu_XiangTuoDongJieGou::rg_LieBiaoShu_XiangTuoDongJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_LieBiaoShu_XiangTuoDongJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_LieBiaoShu_XiangTuoDongJieGou::_IsSelfEqual (const rg_LieBiaoShu_XiangTuoDongJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_LieBiaoShu_XiangTuoDongJieGou::_CopySelfFrom (const rg_LieBiaoShu_XiangTuoDongJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_LieBiaoShiTu_XiangJieGou::rg_LieBiaoShiTu_XiangJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_LieBiaoShiTu_XiangJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_LieBiaoShiTu_XiangJieGou::_IsSelfEqual (const rg_LieBiaoShiTu_XiangJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_LieBiaoShiTu_XiangJieGou::_CopySelfFrom (const rg_LieBiaoShiTu_XiangJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_LieBiao_XiangJieGou::rg_LieBiao_XiangJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_LieBiao_XiangJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_LieBiao_XiangJieGou::_IsSelfEqual (const rg_LieBiao_XiangJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_LieBiao_XiangJieGou::_CopySelfFrom (const rg_LieBiao_XiangJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_LieBiao_TouXiangJieGou::rg_LieBiao_TouXiangJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_LieBiao_TouXiangJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_LieBiao_TouXiangJieGou::_IsSelfEqual (const rg_LieBiao_TouXiangJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_LieBiao_TouXiangJieGou::_CopySelfFrom (const rg_LieBiao_TouXiangJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_ShuXingKuang_XiangJieGou::rg_ShuXingKuang_XiangJieGou ()
{
    _VolObjectInitMembers ();
}

void rg_ShuXingKuang_XiangJieGou::_VolObjectInitMembers ()
{
    _OnInitExtra ();
}

BOOL rg_ShuXingKuang_XiangJieGou::_IsSelfEqual (const rg_ShuXingKuang_XiangJieGou& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_ShuXingKuang_XiangJieGou::_CopySelfFrom (const rg_ShuXingKuang_XiangJieGou& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

}
