
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VPKG_RG_VOLCANO_BASE_W_STARTUP_H__
#define __VPKG_RG_VOLCANO_BASE_W_STARTUP_H__

int gCallStartupMethod ();
CVolRuntimeClass* gGetStartupRuntimeClass ();

#endif  // __VPKG_RG_VOLCANO_BASE_W_STARTUP_H__
